//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hi_TechDistributionInc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorBook
    {
        public int AuthorId { get; set; }
        public long ISBN { get; set; }
        public int YearPublished { get; set; }
        public string Edition { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Book Book { get; set; }
    }
}
